In [ ]:
import pandas as pd

In [ ]:
customers = pd.read_csv('/content/blinkit_customers.csv')

customers.head()

,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,avg_order_value
0,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,451.92
1,22077605,Megha Sachar,vedant45@example.com,915123179717,"51/302, Buch Chowk\nSrinagar-570271",Aligarh,149394,2024-06-18,Inactive,4,825.48
2,47822591,Hema Bahri,samiazaan@example.com,910034076149,"941\nAnne Street, Darbhanga 186125",Begusarai,621411,2024-09-25,Regular,17,1969.81
3,79726146,Zaitra Vig,ishanvi87@example.org,916264232390,"43/94, Ghosh, Alappuzha 635655",Kozhikode,826054,2023-10-04,New,4,220.09
4,57102800,Januja Verma,atideshpande@example.org,917293526596,"06\nOm, Ambarnath 477463",Ichalkaranji,730539,2024-03-22,Inactive,14,578.14

In [ ]:
customers = pd.read_csv('/content/blinkit_customers.csv')

orders = pd.read_csv('/content/blinkit_orders.csv')

order_items = pd.read_csv('/content/blinkit_order_items.csv')

products = pd.read_csv('/content/blinkit_products.csv')

inventory = pd.read_csv('/content/blinkit_inventory.csv')

delivery = pd.read_csv('/content/blinkit_delivery_performance.csv')

feedback = pd.read_csv('/content/blinkit_customer_feedback.csv')

marketing = pd.read_csv('/content/blinkit_marketing_performance.csv')

print("All files loaded successfully")

All files loaded successfully

In [ ]:
datasets = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "products": products,
    "inventory": inventory,
    "delivery": delivery,
    "feedback": feedback,
    "marketing": marketing
}

for name, df in datasets.items():
    print("="*50)
    print(name)
    print(df.shape)
    print(df.columns.tolist())

==================================================
customers
(2500, 11)
['customer_id', 'customer_name', 'email', 'phone', 'address', 'area', 'pincode', 'registration_date', 'customer_segment', 'total_orders', 'avg_order_value']
==================================================
orders
(5000, 10)
['order_id', 'customer_id', 'order_date', 'promised_delivery_time', 'actual_delivery_time', 'delivery_status', 'order_total', 'payment_method', 'delivery_partner_id', 'store_id']
==================================================
order_items
(5000, 4)
['order_id', 'product_id', 'quantity', 'unit_price']
==================================================
products
(268, 10)
['product_id', 'product_name', 'category', 'brand', 'price', 'mrp', 'margin_percentage', 'shelf_life_days', 'min_stock_level', 'max_stock_level']
==================================================
inventory
(75172, 4)
['product_id', 'date', 'stock_received', 'damaged_stock']
==================================================
delivery
(5000, 8)
['order_id', 'delivery_partner_id', 'promised_time', 'actual_time', 'delivery_time_minutes', 'distance_km', 'delivery_status', 'reasons_if_delayed']
==================================================
feedback
(5000, 8)
['feedback_id', 'order_id', 'customer_id', 'rating', 'feedback_text', 'feedback_category', 'sentiment', 'feedback_date']
==================================================
marketing
(5400, 11)
['campaign_id', 'campaign_name', 'date', 'target_audience', 'channel', 'impressions', 'clicks', 'conversions', 'spend', 'revenue_generated', 'roas']

In [ ]:
datasets = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "products": products,
    "inventory": inventory,
    "delivery": delivery,
    "feedback": feedback,
    "marketing": marketing
}

for name, df in datasets.items():
    print("="*60)
    print(f"TABLE: {name}")
    print(f"Rows: {df.shape[0]}")
    print(f"Columns: {df.shape[1]}")
    print("Column Names:")
    print(df.columns.tolist())
    print()

============================================================
TABLE: customers
Rows: 2500
Columns: 11
Column Names:
['customer_id', 'customer_name', 'email', 'phone', 'address', 'area', 'pincode', 'registration_date', 'customer_segment', 'total_orders', 'avg_order_value']

============================================================
TABLE: orders
Rows: 5000
Columns: 10
Column Names:
['order_id', 'customer_id', 'order_date', 'promised_delivery_time', 'actual_delivery_time', 'delivery_status', 'order_total', 'payment_method', 'delivery_partner_id', 'store_id']

============================================================
TABLE: order_items
Rows: 5000
Columns: 4
Column Names:
['order_id', 'product_id', 'quantity', 'unit_price']

============================================================
TABLE: products
Rows: 268
Columns: 10
Column Names:
['product_id', 'product_name', 'category', 'brand', 'price', 'mrp', 'margin_percentage', 'shelf_life_days', 'min_stock_level', 'max_stock_level']

============================================================
TABLE: inventory
Rows: 75172
Columns: 4
Column Names:
['product_id', 'date', 'stock_received', 'damaged_stock']

============================================================
TABLE: delivery
Rows: 5000
Columns: 8
Column Names:
['order_id', 'delivery_partner_id', 'promised_time', 'actual_time', 'delivery_time_minutes', 'distance_km', 'delivery_status', 'reasons_if_delayed']

============================================================
TABLE: feedback
Rows: 5000
Columns: 8
Column Names:
['feedback_id', 'order_id', 'customer_id', 'rating', 'feedback_text', 'feedback_category', 'sentiment', 'feedback_date']

============================================================
TABLE: marketing
Rows: 5400
Columns: 11
Column Names:
['campaign_id', 'campaign_name', 'date', 'target_audience', 'channel', 'impressions', 'clicks', 'conversions', 'spend', 'revenue_generated', 'roas']

In [ ]:
for name, df in datasets.items():
    print("="*60)
    print(name)
    print(df.dtypes)
    print()

============================================================
customers
customer_id            int64
customer_name         object
email                 object
phone                  int64
address               object
area                  object
pincode                int64
registration_date     object
customer_segment      object
total_orders           int64
avg_order_value      float64
dtype: object

============================================================
orders
order_id                    int64
customer_id                 int64
order_date                 object
promised_delivery_time     object
actual_delivery_time       object
delivery_status            object
order_total               float64
payment_method             object
delivery_partner_id         int64
store_id                    int64
dtype: object

============================================================
order_items
order_id        int64
product_id      int64
quantity        int64
unit_price    float64
dtype: object

============================================================
products
product_id             int64
product_name          object
category              object
brand                 object
price                float64
mrp                  float64
margin_percentage    float64
shelf_life_days        int64
min_stock_level        int64
max_stock_level        int64
dtype: object

============================================================
inventory
product_id         int64
date              object
stock_received     int64
damaged_stock      int64
dtype: object

============================================================
delivery
order_id                   int64
delivery_partner_id        int64
promised_time             object
actual_time               object
delivery_time_minutes    float64
distance_km              float64
delivery_status           object
reasons_if_delayed        object
dtype: object

============================================================
feedback
feedback_id           int64
order_id              int64
customer_id           int64
rating                int64
feedback_text        object
feedback_category    object
sentiment            object
feedback_date        object
dtype: object

============================================================
marketing
campaign_id            int64
campaign_name         object
date                  object
target_audience       object
channel               object
impressions            int64
clicks                 int64
conversions            int64
spend                float64
revenue_generated    float64
roas                 float64
dtype: object

In [ ]:
for name, df in datasets.items():
    print("="*60)
    print(name)
    print(df.isnull().sum())
    print()

============================================================
customers
customer_id          0
customer_name        0
email                0
phone                0
address              0
area                 0
pincode              0
registration_date    0
customer_segment     0
total_orders         0
avg_order_value      0
dtype: int64

============================================================
orders
order_id                  0
customer_id               0
order_date                0
promised_delivery_time    0
actual_delivery_time      0
delivery_status           0
order_total               0
payment_method            0
delivery_partner_id       0
store_id                  0
dtype: int64

============================================================
order_items
order_id      0
product_id    0
quantity      0
unit_price    0
dtype: int64

============================================================
products
product_id           0
product_name         0
category             0
brand                0
price                0
mrp                  0
margin_percentage    0
shelf_life_days      0
min_stock_level      0
max_stock_level      0
dtype: int64

============================================================
inventory
product_id        0
date              0
stock_received    0
damaged_stock     0
dtype: int64

============================================================
delivery
order_id                    0
delivery_partner_id         0
promised_time               0
actual_time                 0
delivery_time_minutes       0
distance_km                 0
delivery_status             0
reasons_if_delayed       1902
dtype: int64

============================================================
feedback
feedback_id          0
order_id             0
customer_id          0
rating               0
feedback_text        0
feedback_category    0
sentiment            0
feedback_date        0
dtype: int64

============================================================
marketing
campaign_id          0
campaign_name        0
date                 0
target_audience      0
channel              0
impressions          0
clicks               0
conversions          0
spend                0
revenue_generated    0
roas                 0
dtype: int64

In [ ]:
for name, df in datasets.items():
    print("="*60)
    print(name)
    print("Duplicate Rows:", df.duplicated().sum())

============================================================
customers
Duplicate Rows: 0
============================================================
orders
Duplicate Rows: 0
============================================================
order_items
Duplicate Rows: 0
============================================================
products
Duplicate Rows: 0
============================================================
inventory
Duplicate Rows: 0
============================================================
delivery
Duplicate Rows: 0
============================================================
feedback
Duplicate Rows: 0
============================================================
marketing
Duplicate Rows: 0

In [ ]:
summary = []

for name, df in datasets.items():
    summary.append({
        "Table": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Duplicates": df.duplicated().sum()
    })

import pandas as pd

summary_df = pd.DataFrame(summary)

summary_df

         Table   Rows  Columns  Duplicates
0    customers   2500       11           0
1       orders   5000       10           0
2  order_items   5000        4           0
3     products    268       10           0
4    inventory  75172        4           0
5     delivery   5000        8           0
6     feedback   5000        8           0
7    marketing   5400       11           0

PHASE 2

In [ ]:
# ==========================================================
# PHASE 2 : BUSINESS UNDERSTANDING & DATA PROFILING
# QuickCommerce360
# ==========================================================

import pandas as pd

# ----------------------------------------------------------
# DATASETS
# ----------------------------------------------------------

datasets = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "products": products,
    "inventory": inventory,
    "delivery": delivery,
    "feedback": feedback,
    "marketing": marketing
}

# ==========================================================
# 1. DATASET INVENTORY
# ==========================================================

print("="*80)
print("DATASET INVENTORY")
print("="*80)

for name, df in datasets.items():
    print(f"\nTABLE : {name}")
    print(f"ROWS    : {df.shape[0]}")
    print(f"COLUMNS : {df.shape[1]}")
    print("COLUMN NAMES:")
    print(df.columns.tolist())

# ==========================================================
# 2. DATA TYPES
# ==========================================================

print("\n")
print("="*80)
print("DATA TYPES")
print("="*80)

for name, df in datasets.items():
    print(f"\n{name}")
    print(df.dtypes)

# ==========================================================
# 3. MISSING VALUES
# ==========================================================

print("\n")
print("="*80)
print("MISSING VALUES")
print("="*80)

for name, df in datasets.items():
    print(f"\n{name}")
    print(df.isnull().sum())

# ==========================================================
# 4. DUPLICATES
# ==========================================================

print("\n")
print("="*80)
print("DUPLICATES")
print("="*80)

for name, df in datasets.items():
    print(f"{name} : {df.duplicated().sum()}")

# ==========================================================
# 5. PRIMARY KEY DISCOVERY
# ==========================================================

print("\n")
print("="*80)
print("PRIMARY KEY DISCOVERY")
print("="*80)

for name, df in datasets.items():

    print(f"\n{name}")

    for col in df.columns:

        unique_count = df[col].nunique()

        if unique_count == len(df):
            print(f"Possible Primary Key : {col}")

# ==========================================================
# 6. UNIQUE VALUE ANALYSIS
# ==========================================================

print("\n")
print("="*80)
print("UNIQUE VALUE ANALYSIS")
print("="*80)

for name, df in datasets.items():

    print(f"\n{name}")

    for col in df.columns:
        print(f"{col} : {df[col].nunique()}")

# ==========================================================
# 7. SAMPLE DATA
# ==========================================================

print("\n")
print("="*80)
print("SAMPLE RECORDS")
print("="*80)

for name, df in datasets.items():

    print(f"\n{name}")

    display(df.head())

# ==========================================================
# 8. SUMMARY REPORT
# ==========================================================

summary = []

for name, df in datasets.items():

    summary.append({
        "Table": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Duplicates": df.duplicated().sum(),
        "Missing_Values": df.isnull().sum().sum()
    })

summary_df = pd.DataFrame(summary)

print("\n")
print("="*80)
print("PROJECT SUMMARY")
print("="*80)

display(summary_df)

# ==========================================================
# 9. SAVE REPORT
# ==========================================================

summary_df.to_csv(
    "phase2_summary_report.csv",
    index=False
)

print("\nPhase 2 Completed Successfully")

================================================================================
DATASET INVENTORY
================================================================================

TABLE : customers
ROWS    : 2500
COLUMNS : 11
COLUMN NAMES:
['customer_id', 'customer_name', 'email', 'phone', 'address', 'area', 'pincode', 'registration_date', 'customer_segment', 'total_orders', 'avg_order_value']

TABLE : orders
ROWS    : 5000
COLUMNS : 10
COLUMN NAMES:
['order_id', 'customer_id', 'order_date', 'promised_delivery_time', 'actual_delivery_time', 'delivery_status', 'order_total', 'payment_method', 'delivery_partner_id', 'store_id']

TABLE : order_items
ROWS    : 5000
COLUMNS : 4
COLUMN NAMES:
['order_id', 'product_id', 'quantity', 'unit_price']

TABLE : products
ROWS    : 268
COLUMNS : 10
COLUMN NAMES:
['product_id', 'product_name', 'category', 'brand', 'price', 'mrp', 'margin_percentage', 'shelf_life_days', 'min_stock_level', 'max_stock_level']

TABLE : inventory
ROWS    : 75172
COLUMNS : 4
COLUMN NAMES:
['product_id', 'date', 'stock_received', 'damaged_stock']

TABLE : delivery
ROWS    : 5000
COLUMNS : 8
COLUMN NAMES:
['order_id', 'delivery_partner_id', 'promised_time', 'actual_time', 'delivery_time_minutes', 'distance_km', 'delivery_status', 'reasons_if_delayed']

TABLE : feedback
ROWS    : 5000
COLUMNS : 8
COLUMN NAMES:
['feedback_id', 'order_id', 'customer_id', 'rating', 'feedback_text', 'feedback_category', 'sentiment', 'feedback_date']

TABLE : marketing
ROWS    : 5400
COLUMNS : 11
COLUMN NAMES:
['campaign_id', 'campaign_name', 'date', 'target_audience', 'channel', 'impressions', 'clicks', 'conversions', 'spend', 'revenue_generated', 'roas']


================================================================================
DATA TYPES
================================================================================

customers
customer_id            int64
customer_name         object
email                 object
phone                  int64
address               object
area                  object
pincode                int64
registration_date     object
customer_segment      object
total_orders           int64
avg_order_value      float64
dtype: object

orders
order_id                    int64
customer_id                 int64
order_date                 object
promised_delivery_time     object
actual_delivery_time       object
delivery_status            object
order_total               float64
payment_method             object
delivery_partner_id         int64
store_id                    int64
dtype: object

order_items
order_id        int64
product_id      int64
quantity        int64
unit_price    float64
dtype: object

products
product_id             int64
product_name          object
category              object
brand                 object
price                float64
mrp                  float64
margin_percentage    float64
shelf_life_days        int64
min_stock_level        int64
max_stock_level        int64
dtype: object

inventory
product_id         int64
date              object
stock_received     int64
damaged_stock      int64
dtype: object

delivery
order_id                   int64
delivery_partner_id        int64
promised_time             object
actual_time               object
delivery_time_minutes    float64
distance_km              float64
delivery_status           object
reasons_if_delayed        object
dtype: object

feedback
feedback_id           int64
order_id              int64
customer_id           int64
rating                int64
feedback_text        object
feedback_category    object
sentiment            object
feedback_date        object
dtype: object

marketing
campaign_id            int64
campaign_name         object
date                  object
target_audience       object
channel               object
impressions            int64
clicks                 int64
conversions            int64
spend                float64
revenue_generated    float64
roas                 float64
dtype: object


================================================================================
MISSING VALUES
================================================================================

customers
customer_id          0
customer_name        0
email                0
phone                0
address              0
area                 0
pincode              0
registration_date    0
customer_segment     0
total_orders         0
avg_order_value      0
dtype: int64

orders
order_id                  0
customer_id               0
order_date                0
promised_delivery_time    0
actual_delivery_time      0
delivery_status           0
order_total               0
payment_method            0
delivery_partner_id       0
store_id                  0
dtype: int64

order_items
order_id      0
product_id    0
quantity      0
unit_price    0
dtype: int64

products
product_id           0
product_name         0
category             0
brand                0
price                0
mrp                  0
margin_percentage    0
shelf_life_days      0
min_stock_level      0
max_stock_level      0
dtype: int64

inventory
product_id        0
date              0
stock_received    0
damaged_stock     0
dtype: int64

delivery
order_id                    0
delivery_partner_id         0
promised_time               0
actual_time                 0
delivery_time_minutes       0
distance_km                 0
delivery_status             0
reasons_if_delayed       1902
dtype: int64

feedback
feedback_id          0
order_id             0
customer_id          0
rating               0
feedback_text        0
feedback_category    0
sentiment            0
feedback_date        0
dtype: int64

marketing
campaign_id          0
campaign_name        0
date                 0
target_audience      0
channel              0
impressions          0
clicks               0
conversions          0
spend                0
revenue_generated    0
roas                 0
dtype: int64


================================================================================
DUPLICATES
================================================================================
customers : 0
orders : 0
order_items : 0
products : 0
inventory : 0
delivery : 0
feedback : 0
marketing : 0


================================================================================
PRIMARY KEY DISCOVERY
================================================================================

customers
Possible Primary Key : customer_id
Possible Primary Key : phone
Possible Primary Key : address

orders
Possible Primary Key : order_id
Possible Primary Key : order_date
Possible Primary Key : actual_delivery_time
Possible Primary Key : delivery_partner_id
Possible Primary Key : store_id

order_items
Possible Primary Key : order_id

products
Possible Primary Key : product_id
Possible Primary Key : mrp

inventory

delivery
Possible Primary Key : order_id
Possible Primary Key : delivery_partner_id
Possible Primary Key : actual_time

feedback
Possible Primary Key : feedback_id
Possible Primary Key : order_id

marketing
Possible Primary Key : campaign_id


================================================================================
UNIQUE VALUE ANALYSIS
================================================================================

customers
customer_id : 2500
customer_name : 2491
email : 2496
phone : 2500
address : 2500
area : 316
pincode : 2494
registration_date : 589
customer_segment : 4
total_orders : 20
avg_order_value : 2487

orders
order_id : 5000
customer_id : 2172
order_date : 5000
promised_delivery_time : 4999
actual_delivery_time : 5000
delivery_status : 3
order_total : 4550
payment_method : 4
delivery_partner_id : 5000
store_id : 5000

order_items
order_id : 5000
product_id : 268
quantity : 3
unit_price : 267

products
product_id : 268
product_name : 51
category : 11
brand : 267
price : 267
mrp : 268
margin_percentage : 6
shelf_life_days : 5
min_stock_level : 21
max_stock_level : 51

inventory
product_id : 268
date : 600
stock_received : 4
damaged_stock : 2

delivery
order_id : 5000
delivery_partner_id : 5000
promised_time : 4999
actual_time : 5000
delivery_time_minutes : 36
distance_km : 451
delivery_status : 3
reasons_if_delayed : 1

feedback
feedback_id : 5000
order_id : 5000
customer_id : 2172
rating : 5
feedback_text : 25
feedback_category : 4
sentiment : 3
feedback_date : 600

marketing
campaign_id : 5400
campaign_name : 9
date : 600
target_audience : 4
channel : 4
impressions : 4058
clicks : 899
conversions : 91
spend : 5356
revenue_generated : 5386
roas : 251


================================================================================
SAMPLE RECORDS
================================================================================

customers

,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,avg_order_value
0,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,451.92
1,22077605,Megha Sachar,vedant45@example.com,915123179717,"51/302, Buch Chowk\nSrinagar-570271",Aligarh,149394,2024-06-18,Inactive,4,825.48
2,47822591,Hema Bahri,samiazaan@example.com,910034076149,"941\nAnne Street, Darbhanga 186125",Begusarai,621411,2024-09-25,Regular,17,1969.81
3,79726146,Zaitra Vig,ishanvi87@example.org,916264232390,"43/94, Ghosh, Alappuzha 635655",Kozhikode,826054,2023-10-04,New,4,220.09
4,57102800,Januja Verma,atideshpande@example.org,917293526596,"06\nOm, Ambarnath 477463",Ichalkaranji,730539,2024-03-22,Inactive,14,578.14

orders

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
0,1961864118,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,On Time,3197.07,Cash,63230,4771
1,1549769649,9573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,On Time,976.55,Cash,14983,7534
2,9185164487,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,On Time,839.05,UPI,39859,9886
3,9644738826,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,On Time,440.23,Card,61497,7917
4,5427684290,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,On Time,2526.68,Cash,84315,2741

order_items

     order_id  product_id  quantity  unit_price
0  1961864118      642612         3      517.03
1  1549769649      378676         1      881.42
2  9185164487      741341         2      923.84
3  9644738826      561860         1      874.78
4  5427684290      602241         2      976.55

products

,product_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
0,153019,Onions,Fruits & Vegetables,Aurora LLC,947.95,1263.93,25.0,3,13,88
1,11422,Potatoes,Fruits & Vegetables,Ramaswamy-Tata,127.16,169.55,25.0,3,20,65
2,669378,Potatoes,Fruits & Vegetables,Chadha and Sons,212.14,282.85,25.0,3,23,70
3,848226,Tomatoes,Fruits & Vegetables,Barad and Sons,209.59,279.45,25.0,3,10,51
4,890623,Onions,Fruits & Vegetables,"Sangha, Nagar and Varty",354.52,472.69,25.0,3,27,55

inventory

   product_id        date  stock_received  damaged_stock
0      153019  17-03-2023               4              2
1      848226  17-03-2023               4              2
2      965755  17-03-2023               1              0
3       39154  17-03-2023               4              0
4       34186  17-03-2023               3              2

delivery

,order_id,delivery_partner_id,promised_time,actual_time,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed
0,1961864118,63230,2024-07-17 08:52:01,2024-07-17 08:47:01,-5.0,0.96,On Time,NaN
1,1549769649,14983,2024-05-28 13:25:29,2024-05-28 13:27:29,2.0,0.98,On Time,Traffic
2,9185164487,39859,2024-09-23 13:25:12,2024-09-23 13:29:12,4.0,3.83,On Time,Traffic
3,9644738826,61497,2023-11-24 16:34:56,2023-11-24 16:33:56,-1.0,2.76,On Time,NaN
4,5427684290,84315,2023-11-20 05:17:39,2023-11-20 05:18:39,1.0,2.63,On Time,Traffic

feedback

,feedback_id,order_id,customer_id,rating,feedback_text,feedback_category,sentiment,feedback_date
0,2234710,1961864118,30065862,4,"It was okay, nothing special.",Delivery,Neutral,2024-07-17
1,5450964,1549769649,9573071,3,The order was incorrect.,App Experience,Negative,2024-05-28
2,482108,9185164487,45477575,3,"It was okay, nothing special.",App Experience,Neutral,2024-09-23
3,4823104,9644738826,88067569,4,The product met my expectations.,App Experience,Neutral,2023-11-24
4,3537464,5427684290,83298567,3,Product was damaged during delivery.,Delivery,Negative,2023-11-20

marketing

,campaign_id,campaign_name,date,target_audience,channel,impressions,clicks,conversions,spend,revenue_generated,roas
0,548299,New User Discount,2024-11-05,Premium,App,3130,163,78,1431.85,4777.75,3.60
1,390914,Weekend Special,2024-11-05,Inactive,App,3925,494,45,4506.34,6238.11,2.98
2,834385,Festival Offer,2024-11-05,Inactive,Email,7012,370,78,4524.23,2621.00,2.95
3,241523,Flash Sale,2024-11-05,Inactive,SMS,1115,579,86,3622.79,2955.00,2.84
4,595111,Membership Drive,2024-11-05,New Users,Email,7172,795,54,2888.99,8951.81,2.22

================================================================================
PROJECT SUMMARY
================================================================================

         Table   Rows  Columns  Duplicates  Missing_Values
0    customers   2500       11           0               0
1       orders   5000       10           0               0
2  order_items   5000        4           0               0
3     products    268       10           0               0
4    inventory  75172        4           0               0
5     delivery   5000        8           0            1902
6     feedback   5000        8           0               0
7    marketing   5400       11           0               0

Phase 2 Completed Successfully

PHASE 3

In [ ]:
# =====================================================
# PHASE 3 : STAR SCHEMA CREATION
# QuickCommerce360
# =====================================================

import pandas as pd

# =====================================================
# 1. CREATE REVENUE COLUMN
# =====================================================

order_items["revenue"] = (
    order_items["quantity"] *
    order_items["unit_price"]
)

print("Revenue Created")

# =====================================================
# 2. FACT ORDERS
# =====================================================

fact_orders = (
    orders
    .merge(
        order_items,
        on="order_id",
        how="inner"
    )
)

fact_orders = fact_orders[
    [
        "order_id",
        "customer_id",
        "product_id",
        "order_date",
        "quantity",
        "unit_price",
        "revenue",
        "order_total",
        "payment_method"
    ]
]

print("Fact Orders Created")

# =====================================================
# 3. FACT DELIVERY
# =====================================================

fact_delivery = delivery[
    [
        "order_id",
        "delivery_partner_id",
        "delivery_time_minutes",
        "distance_km",
        "delivery_status"
    ]
]

print("Fact Delivery Created")

# =====================================================
# 4. FACT FEEDBACK
# =====================================================

fact_feedback = feedback[
    [
        "feedback_id",
        "order_id",
        "customer_id",
        "rating",
        "sentiment",
        "feedback_category"
    ]
]

print("Fact Feedback Created")

# =====================================================
# 5. FACT MARKETING
# =====================================================

fact_marketing = marketing[
    [
        "campaign_id",
        "date",
        "channel",
        "impressions",
        "clicks",
        "conversions",
        "spend",
        "revenue_generated",
        "roas"
    ]
]

print("Fact Marketing Created")

# =====================================================
# 6. DIM CUSTOMER
# =====================================================

dim_customer = customers[
    [
        "customer_id",
        "customer_segment",
        "area",
        "pincode",
        "registration_date"
    ]
].drop_duplicates()

print("Dim Customer Created")

# =====================================================
# 7. DIM PRODUCT
# =====================================================

dim_product = products[
    [
        "product_id",
        "product_name",
        "category",
        "brand",
        "shelf_life_days"
    ]
].drop_duplicates()

print("Dim Product Created")

# =====================================================
# 8. DIM DATE
# =====================================================

orders["order_date"] = pd.to_datetime(
    orders["order_date"]
)

dim_date = pd.DataFrame()

dim_date["date"] = orders["order_date"].dt.date

dim_date["day"] = orders["order_date"].dt.day

dim_date["month"] = orders["order_date"].dt.month

dim_date["quarter"] = orders["order_date"].dt.quarter

dim_date["year"] = orders["order_date"].dt.year

dim_date["weekday"] = orders["order_date"].dt.day_name()

dim_date = dim_date.drop_duplicates()

print("Dim Date Created")

# =====================================================
# 9. DISPLAY SHAPES
# =====================================================

print("\n")
print("="*50)

print("FACT ORDERS :", fact_orders.shape)

print("FACT DELIVERY :", fact_delivery.shape)

print("FACT FEEDBACK :", fact_feedback.shape)

print("FACT MARKETING :", fact_marketing.shape)

print("DIM CUSTOMER :", dim_customer.shape)

print("DIM PRODUCT :", dim_product.shape)

print("DIM DATE :", dim_date.shape)

print("="*50)

# =====================================================
# 10. SAVE TABLES
# =====================================================

fact_orders.to_csv(
    "fact_orders.csv",
    index=False
)

fact_delivery.to_csv(
    "fact_delivery.csv",
    index=False
)

fact_feedback.to_csv(
    "fact_feedback.csv",
    index=False
)

fact_marketing.to_csv(
    "fact_marketing.csv",
    index=False
)

dim_customer.to_csv(
    "dim_customer.csv",
    index=False
)

dim_product.to_csv(
    "dim_product.csv",
    index=False
)

dim_date.to_csv(
    "dim_date.csv",
    index=False
)

print("\nPhase 3 Completed Successfully")

Revenue Created
Fact Orders Created
Fact Delivery Created
Fact Feedback Created
Fact Marketing Created
Dim Customer Created
Dim Product Created
Dim Date Created


==================================================
FACT ORDERS : (5000, 9)
FACT DELIVERY : (5000, 5)
FACT FEEDBACK : (5000, 6)
FACT MARKETING : (5400, 9)
DIM CUSTOMER : (2500, 5)
DIM PRODUCT : (268, 5)
DIM DATE : (600, 6)
==================================================

Phase 3 Completed Successfully

PHASE 4

In [ ]:
# =====================================================
# PHASE 4 : DATA QUALITY FRAMEWORK & ETL MONITORING
# QuickCommerce360
# =====================================================

import pandas as pd
from datetime import datetime

print("="*60)
print("PHASE 4 STARTED")
print("="*60)

# =====================================================
# 1. DATA QUALITY REPORT
# =====================================================

quality_report = []

tables = {
    "fact_orders": fact_orders,
    "fact_delivery": fact_delivery,
    "fact_feedback": fact_feedback,
    "fact_marketing": fact_marketing,
    "dim_customer": dim_customer,
    "dim_product": dim_product,
    "dim_date": dim_date
}

for table_name, df in tables.items():

    quality_report.append({
        "table_name": table_name,
        "rows": len(df),
        "columns": len(df.columns),
        "missing_values": df.isnull().sum().sum(),
        "duplicate_rows": df.duplicated().sum()
    })

quality_report_df = pd.DataFrame(quality_report)

print("\nDATA QUALITY REPORT")
display(quality_report_df)

# =====================================================
# 2. REVENUE VALIDATION
# =====================================================

print("\n")
print("="*60)
print("REVENUE VALIDATION")
print("="*60)

total_revenue = round(fact_orders["revenue"].sum(),2)

avg_revenue = round(fact_orders["revenue"].mean(),2)

max_revenue = round(fact_orders["revenue"].max(),2)

print("Total Revenue :", total_revenue)
print("Average Revenue :", avg_revenue)
print("Maximum Revenue :", max_revenue)

# =====================================================
# 3. DELIVERY DATA QUALITY CHECK
# =====================================================

print("\n")
print("="*60)
print("DELIVERY DATA QUALITY")
print("="*60)

negative_delivery_time = fact_delivery[
    fact_delivery["delivery_time_minutes"] < 0
]

print(
    "Negative Delivery Time Records :",
    len(negative_delivery_time)
)

# =====================================================
# 4. INVENTORY DATA QUALITY CHECK
# =====================================================

print("\n")
print("="*60)
print("INVENTORY DATA QUALITY")
print("="*60)

invalid_inventory = inventory[
    inventory["damaged_stock"] >
    inventory["stock_received"]
]

print(
    "Invalid Inventory Records :",
    len(invalid_inventory)
)

# =====================================================
# 5. CUSTOMER DATA QUALITY CHECK
# =====================================================

print("\n")
print("="*60)
print("CUSTOMER DATA QUALITY")
print("="*60)

duplicate_customers = customers.duplicated().sum()

print(
    "Duplicate Customers :",
    duplicate_customers
)

# =====================================================
# 6. PRODUCT DATA QUALITY CHECK
# =====================================================

print("\n")
print("="*60)
print("PRODUCT DATA QUALITY")
print("="*60)

invalid_price = products[
    products["price"] <= 0
]

print(
    "Invalid Product Price Records :",
    len(invalid_price)
)

# =====================================================
# 7. BUSINESS RULE VALIDATION
# =====================================================

print("\n")
print("="*60)
print("BUSINESS RULE VALIDATION")
print("="*60)

invalid_quantity = fact_orders[
    fact_orders["quantity"] <= 0
]

print(
    "Invalid Quantity Records :",
    len(invalid_quantity)
)

invalid_revenue = fact_orders[
    fact_orders["revenue"] <= 0
]

print(
    "Invalid Revenue Records :",
    len(invalid_revenue)
)

# =====================================================
# 8. ETL AUDIT LOG
# =====================================================

etl_audit_log = pd.DataFrame({
    "job_name": [
        "fact_orders_load",
        "fact_delivery_load",
        "fact_feedback_load",
        "fact_marketing_load",
        "dim_customer_load",
        "dim_product_load",
        "dim_date_load"
    ],

    "execution_time": [
        datetime.now()
    ] * 7,

    "status": [
        "SUCCESS"
    ] * 7,

    "rows_processed": [
        len(fact_orders),
        len(fact_delivery),
        len(fact_feedback),
        len(fact_marketing),
        len(dim_customer),
        len(dim_product),
        len(dim_date)
    ]
})

print("\nETL AUDIT LOG")
display(etl_audit_log)

# =====================================================
# 9. SAVE REPORTS
# =====================================================

quality_report_df.to_csv(
    "quality_report.csv",
    index=False
)

etl_audit_log.to_csv(
    "etl_audit_log.csv",
    index=False
)

print("\nReports Saved")

# =====================================================
# 10. PHASE 4 SUMMARY
# =====================================================

phase4_summary = pd.DataFrame({
    "Metric":[
        "Total Revenue",
        "Average Revenue",
        "Max Revenue",
        "Negative Delivery Records",
        "Invalid Inventory Records"
    ],
    "Value":[
        total_revenue,
        avg_revenue,
        max_revenue,
        len(negative_delivery_time),
        len(invalid_inventory)
    ]
})

print("\nPHASE 4 SUMMARY")
display(phase4_summary)

print("\n")
print("="*60)
print("PHASE 4 COMPLETED SUCCESSFULLY")
print("="*60)

============================================================
PHASE 4 STARTED
============================================================

DATA QUALITY REPORT

       table_name  rows  columns  missing_values  duplicate_rows
0     fact_orders  5000        9               0               0
1   fact_delivery  5000        5               0               0
2   fact_feedback  5000        6               0               0
3  fact_marketing  5400        9               0               0
4    dim_customer  2500        5               0               0
5     dim_product   268        5               0               0
6        dim_date   600        6               0               0

============================================================
REVENUE VALIDATION
============================================================
Total Revenue : 4972415.43
Average Revenue : 994.48
Maximum Revenue : 2987.94


============================================================
DELIVERY DATA QUALITY
============================================================
Negative Delivery Time Records : 1563


============================================================
INVENTORY DATA QUALITY
============================================================
Invalid Inventory Records : 29255


============================================================
CUSTOMER DATA QUALITY
============================================================
Duplicate Customers : 0


============================================================
PRODUCT DATA QUALITY
============================================================
Invalid Product Price Records : 0


============================================================
BUSINESS RULE VALIDATION
============================================================
Invalid Quantity Records : 0
Invalid Revenue Records : 0

ETL AUDIT LOG

              job_name             execution_time   status  rows_processed
0     fact_orders_load 2026-06-04 07:55:25.900442  SUCCESS            5000
1   fact_delivery_load 2026-06-04 07:55:25.900442  SUCCESS            5000
2   fact_feedback_load 2026-06-04 07:55:25.900442  SUCCESS            5000
3  fact_marketing_load 2026-06-04 07:55:25.900442  SUCCESS            5400
4    dim_customer_load 2026-06-04 07:55:25.900442  SUCCESS            2500
5     dim_product_load 2026-06-04 07:55:25.900442  SUCCESS             268
6        dim_date_load 2026-06-04 07:55:25.900442  SUCCESS             600

Reports Saved

PHASE 4 SUMMARY

                      Metric       Value
0              Total Revenue  4972415.43
1            Average Revenue      994.48
2                Max Revenue     2987.94
3  Negative Delivery Records     1563.00
4  Invalid Inventory Records    29255.00

============================================================
PHASE 4 COMPLETED SUCCESSFULLY
============================================================

PHASE 5

In [ ]:
# =====================================================
# PHASE 5 : FEATURE ENGINEERING & BUSINESS KPIs
# QuickCommerce360
# =====================================================

import pandas as pd
import numpy as np

print("="*60)
print("PHASE 5 STARTED")
print("="*60)

# =====================================================
# 1. CUSTOMER KPIs
# =====================================================

customer_kpis = (
    fact_orders
    .groupby("customer_id")
    .agg(
        total_orders=("order_id","count"),
        total_revenue=("revenue","sum"),
        avg_order_value=("revenue","mean")
    )
    .reset_index()
)

customer_kpis["customer_lifetime_value"] = (
    customer_kpis["total_revenue"]
)

customer_kpis["purchase_frequency"] = (
    customer_kpis["total_orders"]
)

print("Customer KPIs Created")

# =====================================================
# 2. CUSTOMER SEGMENTATION
# =====================================================

customer_kpis["customer_segment"] = pd.qcut(
    customer_kpis["customer_lifetime_value"],
    q=3,
    labels=["Bronze","Silver","Gold"]
)

print("Customer Segmentation Created")

# =====================================================
# 3. PRODUCT KPIs
# =====================================================

product_kpis = (
    fact_orders
    .groupby("product_id")
    .agg(
        total_quantity=("quantity","sum"),
        total_revenue=("revenue","sum")
    )
    .reset_index()
)

product_kpis = (
    product_kpis
    .merge(
        dim_product,
        on="product_id",
        how="left"
    )
)

print("Product KPIs Created")

# =====================================================
# 4. CATEGORY KPIs
# =====================================================

category_kpis = (
    product_kpis
    .groupby("category")
    .agg(
        category_revenue=("total_revenue","sum"),
        quantity_sold=("total_quantity","sum")
    )
    .reset_index()
)

print("Category KPIs Created")

# =====================================================
# 5. DELIVERY KPIs
# =====================================================

delivery_kpis = pd.DataFrame()

delivery_kpis["avg_delivery_time"] = [
    fact_delivery["delivery_time_minutes"].mean()
]

delivery_kpis["avg_distance"] = [
    fact_delivery["distance_km"].mean()
]

delivery_kpis["on_time_deliveries"] = [
    len(
        fact_delivery[
            fact_delivery["delivery_status"]=="On Time"
        ]
    )
]

delivery_kpis["late_deliveries"] = [
    len(
        fact_delivery[
            fact_delivery["delivery_status"]!="On Time"
        ]
    )
]

delivery_kpis["delivery_sla_percent"] = [
    (
        len(
            fact_delivery[
                fact_delivery["delivery_status"]=="On Time"
            ]
        )
        /
        len(fact_delivery)
    ) * 100
]

print("Delivery KPIs Created")

# =====================================================
# 6. FEEDBACK KPIs
# =====================================================

feedback_kpis = (
    fact_feedback
    .groupby("sentiment")
    .size()
    .reset_index(name="count")
)

avg_rating = fact_feedback["rating"].mean()

print("Feedback KPIs Created")

# =====================================================
# 7. MARKETING KPIs
# =====================================================

marketing_kpis = marketing.copy()

marketing_kpis["conversion_rate"] = (
    marketing_kpis["conversions"]
    /
    marketing_kpis["clicks"]
) * 100

marketing_kpis["cost_per_conversion"] = (
    marketing_kpis["spend"]
    /
    marketing_kpis["conversions"]
)

print("Marketing KPIs Created")

# =====================================================
# 8. RFM ANALYSIS
# =====================================================

fact_orders["order_date"] = pd.to_datetime(
    fact_orders["order_date"]
)

snapshot_date = (
    fact_orders["order_date"].max()
    + pd.Timedelta(days=1)
)

rfm = (
    fact_orders
    .groupby("customer_id")
    .agg({
        "order_date":
            lambda x: (
                snapshot_date - x.max()
            ).days,
        "order_id":"count",
        "revenue":"sum"
    })
)

rfm.columns = [
    "Recency",
    "Frequency",
    "Monetary"
]

rfm = rfm.reset_index()

print("RFM Analysis Created")

# =====================================================
# 9. TOP CUSTOMERS
# =====================================================

top_customers = (
    customer_kpis
    .sort_values(
        "total_revenue",
        ascending=False
    )
    .head(10)
)

print("Top Customers Created")

# =====================================================
# 10. SAVE FILES
# =====================================================

customer_kpis.to_csv(
    "customer_kpis.csv",
    index=False
)

product_kpis.to_csv(
    "product_kpis.csv",
    index=False
)

category_kpis.to_csv(
    "category_kpis.csv",
    index=False
)

delivery_kpis.to_csv(
    "delivery_kpis.csv",
    index=False
)

feedback_kpis.to_csv(
    "feedback_kpis.csv",
    index=False
)

marketing_kpis.to_csv(
    "marketing_kpis.csv",
    index=False
)

rfm.to_csv(
    "rfm_segmentation.csv",
    index=False
)

top_customers.to_csv(
    "top_customers.csv",
    index=False
)

# =====================================================
# 11. SUMMARY
# =====================================================

print("\n")
print("="*60)
print("PHASE 5 SUMMARY")
print("="*60)

print("Customer KPI Records :", len(customer_kpis))
print("Product KPI Records :", len(product_kpis))
print("Category KPI Records :", len(category_kpis))
print("Marketing KPI Records :", len(marketing_kpis))
print("RFM Records :", len(rfm))

print("\nPhase 5 Completed Successfully")

============================================================
PHASE 5 STARTED
============================================================
Customer KPIs Created
Customer Segmentation Created
Product KPIs Created
Category KPIs Created
Delivery KPIs Created
Feedback KPIs Created
Marketing KPIs Created
RFM Analysis Created
Top Customers Created


============================================================
PHASE 5 SUMMARY
============================================================
Customer KPI Records : 2172
Product KPI Records : 268
Category KPI Records : 11
Marketing KPI Records : 5400
RFM Records : 2172

Phase 5 Completed Successfully

In [ ]:
from google.colab import files

files.download("fact_orders.csv")
files.download("fact_delivery.csv")
files.download("fact_feedback.csv")
files.download("fact_marketing.csv")

files.download("dim_customer.csv")
files.download("dim_product.csv")
files.download("dim_date.csv")

FileNotFoundError: Cannot find file: fact_orders.csv

In [ ]:
import os

for file in os.listdir():
    print(file)

.config
sample_data

In [ ]:
print(type(fact_orders))
print(type(dim_customer))

NameError: name 'fact_orders' is not defined

In [ ]:
import pandas as pd

customers = pd.read_csv('/content/blinkit_customers.csv')
orders = pd.read_csv('/content/blinkit_orders.csv')
order_items = pd.read_csv('/content/blinkit_order_items.csv')
products = pd.read_csv('/content/blinkit_products.csv')
inventory = pd.read_csv('/content/blinkit_inventory.csv')
delivery = pd.read_csv('/content/blinkit_delivery_performance.csv')
feedback = pd.read_csv('/content/blinkit_customer_feedback.csv')
marketing = pd.read_csv('/content/blinkit_marketing_performance.csv')

print("All datasets loaded successfully")

All datasets loaded successfully

In [ ]:
fact_orders.to_csv("fact_orders.csv", index=False)
fact_delivery.to_csv("fact_delivery.csv", index=False)
fact_feedback.to_csv("fact_feedback.csv", index=False)
fact_marketing.to_csv("fact_marketing.csv", index=False)

dim_customer.to_csv("dim_customer.csv", index=False)
dim_product.to_csv("dim_product.csv", index=False)
dim_date.to_csv("dim_date.csv", index=False)

print("Warehouse tables saved")

NameError: name 'fact_orders' is not defined

In [ ]:
fact_orders
fact_delivery
fact_feedback
fact_marketing

dim_customer
dim_product
dim_date

NameError: name 'fact_orders' is not defined

In [ ]:
print(customers.shape)
print(orders.shape)
print(order_items.shape)

(2500, 11)
(5000, 10)
(5000, 4)

In [ ]:
fact_orders.to_csv("fact_orders.csv", index=False)
fact_delivery.to_csv("fact_delivery.csv", index=False)
fact_feedback.to_csv("fact_feedback.csv", index=False)
fact_marketing.to_csv("fact_marketing.csv", index=False)

dim_customer.to_csv("dim_customer.csv", index=False)
dim_product.to_csv("dim_product.csv", index=False)
dim_date.to_csv("dim_date.csv", index=False)

print("Saved Successfully")

NameError: name 'fact_orders' is not defined

In [ ]:
order_items_copy = order_items.copy()
order_items_copy["revenue"] = (
    order_items_copy["quantity"] *
    order_items_copy["unit_price"]
)

fact_orders = (
    orders
    .merge(
        order_items_copy,
        on="order_id",
        how="inner"
    )
)

fact_orders = fact_orders[
    [
        "order_id",
        "customer_id",
        "product_id",
        "order_date",
        "quantity",
        "unit_price",
        "revenue",
        "order_total",
        "payment_method"
    ]
]

dim_customer = customers[
    [
        "customer_id",
        "customer_segment",
        "area",
        "pincode",
        "registration_date"
    ]
].drop_duplicates()

print(fact_orders.shape)
print(dim_customer.shape)

(5000, 9)
(2500, 5)

In [ ]:
import pandas as pd

# Ensure orders 'order_date' is datetime for dim_date creation
orders["order_date"] = pd.to_datetime(
    orders["order_date"]
)

# Create 'revenue' column in a copy of order_items
order_items_copy = order_items.copy()
order_items_copy["revenue"] = (
    order_items_copy["quantity"] *
    order_items_copy["unit_price"]
)

# Define fact_orders
fact_orders = (
    orders
    .merge(
        order_items_copy,
        on="order_id",
        how="inner"
    )
)
fact_orders = fact_orders[
    [
        "order_id",
        "customer_id",
        "product_id",
        "order_date",
        "quantity",
        "unit_price",
        "revenue",
        "order_total",
        "payment_method"
    ]
]

# Define fact_delivery
fact_delivery = delivery[
    [
        "order_id",
        "delivery_partner_id",
        "delivery_time_minutes",
        "distance_km",
        "delivery_status"
    ]
]

# Define fact_feedback
fact_feedback = feedback[
    [
        "feedback_id",
        "order_id",
        "customer_id",
        "rating",
        "sentiment",
        "feedback_category"
    ]
]

# Define fact_marketing
fact_marketing = marketing[
    [
        "campaign_id",
        "date",
        "channel",
        "impressions",
        "clicks",
        "conversions",
        "spend",
        "revenue_generated",
        "roas"
    ]
]

# Define dim_customer
dim_customer = customers[
    [
        "customer_id",
        "customer_segment",
        "area",
        "pincode",
        "registration_date"
    ]
].drop_duplicates()

# Define dim_product
dim_product = products[
    [
        "product_id",
        "product_name",
        "category",
        "brand",
        "shelf_life_days"
    ]
].drop_duplicates()

# Define dim_date
dim_date = pd.DataFrame()
dim_date["date"] = orders["order_date"].dt.date
dim_date["day"] = orders["order_date"].dt.day
dim_date["month"] = orders["order_date"].dt.month
dim_date["quarter"] = orders["order_date"].dt.quarter
dim_date["year"] = orders["order_date"].dt.year
dim_date["weekday"] = orders["order_date"].dt.day_name()
dim_date = dim_date.drop_duplicates()

# Save tables to CSV
fact_orders.to_csv("fact_orders.csv", index=False)
fact_delivery.to_csv("fact_delivery.csv", index=False)
fact_feedback.to_csv("fact_feedback.csv", index=False)
fact_marketing.to_csv("fact_marketing.csv", index=False)

dim_customer.to_csv("dim_customer.csv", index=False)
dim_product.to_csv("dim_product.csv", index=False)
dim_date.to_csv("dim_date.csv", index=False)

print("Saved Successfully")

Saved Successfully

In [ ]:
from google.colab import files

files.download("fact_orders.csv")
files.download("fact_delivery.csv")
files.download("fact_feedback.csv")
files.download("fact_marketing.csv")

files.download("dim_customer.csv")
files.download("dim_product.csv")
files.download("dim_date.csv")